### ISSUE TITLE
Dedicated Welcome Views for specific Workspace states

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#23]
As documented in #16, it is possible to adapt the content shown in the extension depending on some conditions. 

We want the extension to detect and render a dedicated Welcome View with optimal UX for each of the following workspace states:

**1. Workspace contains no open folder at all**

```
Welcome to the Radicle extension!

You currently have no folder open in your workspace. In order to use Radicle, you should open a folder containing a git repository.

<Button label="Open Folder" @click="bring up the OS-native dir explorer" @submit="open the selected folder into VS Code's workspace">

To learn more about how to use git and source control in VS Code [read the docs](https://code.visualstudio.com/docs/sourcecontrol/overview).
```

>NOTE:
>In subsequent versions, we could add an additional button to "Clone Repository" with either git or rad depending on URL

**2. Workspace contains no open folder that is git-initialised**

```
Welcome to the Radicle extension!

The folder currently open in your workspace is not a git repository. You can initialize it as a repository and enable source control features powered by git.

<Button label="Initialize Repository" @click="run git init similar to what VS Code's native SCM welcome screen button does">

To learn more about how to use git and source control in VS Code [read the docs](https://code.visualstudio.com/docs/sourcecontrol/overview).
```

>NOTE:
>In subsequent versions, we could have the additional content
>```
> You can directly initialize and publish this folder to Radicle. Once published, you'll have access to advanced source control and project management features powered by both git and Radicle. Your repository will be hosted publicly on the free and peer-to-peer Radicle network.
> <Button label="$(rad-logo) Publish to Radicle" @click="gitInit() && radInit()">
>```

**3. Non-radicle-initialised git repo**

```
Welcome to the Radicle extension!

The git repository currently open in your workspace is not yet published on Radicle.

Please run `rad init` in your terminal after ensuring that you have rad CLI installed on your machine.

Once published, you'll have access to advanced source control and project management features powered by both git and Radicle. Your repository will be hosted publicly on the free and peer-to-peer Radicle network.

To learn more, please read the [Getting Started Guide](https://radicle.xyz/get-started.html).
```

>NOTE:
>In subsequent versions, we could have the alternative content
>```
> <Button label="$(rad-logo) Publish to Radicle" @click="gitInit() && radInit()">
> Note:
> `rad init` creates an additional git remote and does not interfere with your repository's state and configuration in any other way.
>```

**4. Radicle-initialised repo**

In this state, we should show _neither_ of the aforementioned Welcome Views. We can just go ahead with showing the content we have now, without the "NOTE".

![image](https://user-images.githubusercontent.com/7542054/225575002-e8883c3b-9f0f-41bb-a5ec-9eb2866a6cd2.png)

--------------

_The above spec is inspired from the Github and Gitlab extensions as well as the native VS Code SCM._

References:

<table>
<tr>
	<th>
	<th> State 1
	<th> State 2
<tr>
	<td> native SCM
	<td> <img src="https://user-images.githubusercontent.com/7542054/225412538-3e21d792-445a-4b66-907e-910246cab037.png">
	<td> <img src="https://user-images.githubusercontent.com/7542054/225412301-77c6d6bf-626b-4cf0-a84d-1b49c09030cf.png">
<tr>
	<td> Github
	<td> <img src="https://user-images.githubusercontent.com/7542054/225415136-146d7e21-ccc4-4cbb-87cd-d95e246f7940.png">
	<td> <img src="https://user-images.githubusercontent.com/7542054/225414665-b64c0961-8295-4622-940a-be3303aa9e82.png">
<tr>
	<td> Gitlab
	<td> <img src="https://user-images.githubusercontent.com/7542054/225414101-1a54bb3b-b9be-447e-96af-b121d6e01fdf.png">
	<td> <img src="https://user-images.githubusercontent.com/7542054/225414101-1a54bb3b-b9be-447e-96af-b121d6e01fdf.png">
</table>

**Comment by maninak** [comment]
@gsaslis I heavily edited the ticket description for conciseness, spec specificity and to incorporate research findings.

A tangential topic mentioned in the previous version of the description was extracted to a new ticket #25 .

**Comment by gsaslis** [comment]
this looks great, thanks @maninak !

**Comment by maninak** [comment]
While the additional edits to the ticket description were in the right direction, plenty of open questions, implementation complexity and opportunities for improvement came up while getting down and dirty with this ticket. Copies have been further refined and more states have been added.

The states now are:

1. Workspace contains no opened folder at all
2. Workspace contains no opened folder that is git-initialised
3. Non-radicle-initialised git repo
4. Radicle-initialised but not published repo
5. Radicle-published repo but rad CLI is not installed
6. Radicle-published repo with rad CLI installed (default)

To disambiguate between the above states new checks have been implemented e.g. `isRadCliInstalled`, `isRepoRadPublished` etc which can be used as building blocks for upcoming features.

The extension will watch the `.git/config` file for changes and instantly update its internal state upon rad initialization and/or publication of the repo, subsequently updating the UI
as needed.

The extension will also watch default Radicle CLI installation paths (for each OS) as well as the `binaryPath` config in the extension's settings for changes, in case the CLI just got installed (following the troubleshooting guide) and update subsequently the UI as needed.

The above reactivity efforts should negate the need for a VS Code reload in order to detect state changes (important!..) in most use cases.

Additional changes:

- warning/notifying the user of failed/succesful Radicle CLI resolution only when appropriate
    - e.g. if the user just opened vscode to inspect a txt file we won't complain that Radicle CLI isn't installed. We also won't do it during the onboarding flow, unless the user is already at a stage where he needs to use the CLI to move on.
    - In contrast, if the user just broke, or fixed the CLI installation they will be promptly notified with an info/warn message.
    - The warning message can subsequently trigger the troubleshooting flow.
- homogenization of copies across the UI now refering to `rad` as "Radicle CLI binary"
- copy improvements across all of the troubleshooting flow following user feedback
- `getRadCliVersion()` will attempt to return semver format

**Comment by gsaslis** [comment]
Great stuff @maninak ! 

> The extension will watch the .git/config file for changes and instantly update its internal state upon rad initialization and/or publication of the repo, subsequently updating the UI
as needed.

While this is certainly ok for a v0.1, I'm wondering if, in the longer term, we really should be looking at `.git/config` or relying on some `rad` command instead ?

**Comment by maninak** [comment]
The thing is, if we want to reactively do things, we can only do it by watching a file for changes.

We can either be notified of a change _somehow_ (reactive) or poll (procedural). Otherwise, the user has to reload their VS Code for changes to be detected by the extension.

I'm sensing that we might need to eventually work with the heartwood team to have some file-based communication/signaling between rad and its clients.

If that isn't clear enough or doesn't answer all your questions, I'd be happy to explain it further in Zulip or on a call.

**Comment by maninak** [comment]
> does this mean we can use polling for the result of a `rad $command` invocation, or is that just my wishful thinking ?? smile 🤞🏼

Sure, we can put any shell command (including `rad` commands) in a [`setInterval()`](https://developer.mozilla.org/en-US/docs/Web/API/setInterval).

And even with the current implementation, I'm using changes on `.git/config` mostly for signaling (in trying to avoid polling...) to kickstart a subroutine that will still use `rad` itself.

Example:

We're saying here https://github.com/cytechmobile/radicle-vscode-extension/blob/4a8909fbb9056ce7e35a91291bf8813f111ef263/src/utils/fs.ts#L52-L61

```
IF '.git/config' is updated
THEN call isRepoRadInitialised() and set `radicle.isRepoRadInitialised`
```

But if you see its implementation isRepoRadInitialised() actually invokes the CLI https://github.com/cytechmobile/radicle-vscode-extension/blob/4a8909fbb9056ce7e35a91291bf8813f111ef263/src/utils/repo.ts#L30

I agree with you, that many decisions taken will in architecture as well as product will need to be revisited, but it's important for me that at least for now you have this high-level understanding of those inner workings and the rationale behind choosing them.
