### ISSUE TITLE
Add radicle HTTP API endpoint in extension settings

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#26]
In heartwood, we no longer have the concept of multiple seed nodes. Our IDE would only connect to / use a specific node. 

We need the HTTP API to pull information about: 

* projects
  * patches 
  * issues 
  
Because it is not always clear where/how the HTTP endpoint is running, we need to add a single input field in the Radicle settings screen. The field asks for the URL to the seed node API and should include the Fully-Qualified Domain Name (FQDN) - i.e. $protocol://$host:$port/$path (not just a host and a port, because it is also possible to expose the API behind a reverse proxy - e.g. https://radicle.mydomain.com/myapi).

**Comment by gsaslis** [comment]
@maninak correct: this is only about adding the config, so that when the time comes to e.g. list projects that can be cloned ( say, in #29 ) or patches/issues that can be displayed (later on) we know what radicle-httpd we will be hitting.

**Comment by maninak** [comment]
@gsaslis Is there a default value for the endpoint? If yes, which is it?

**Comment by gsaslis** [comment]
@maninak 
1. https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/tree/master/radicle-httpd/src/main.rs#L76 tells us it's port `8080`, but `0.0.0.0` is the _listen_ address and means: `any`. When we are connecting to the API, we would (presumably) be connecting on `localhost` , or `127.0.0.1` - but that also depends on whether the API is deployed natively on the host, or via docker, etc. etc. 
2. A notification, for sure. A troubleshooting flow, not right now. Let's get collaboration through the extension working first. I created https://github.com/cytechmobile/radicle-vscode-extension/issues/37 for that.

**Comment by maninak** [comment]
@gsaslis 

1. so which one is it? `http://localhost:8080` or `http://127.0.0.1:8080`? (theoretically they should be the same, right? Unless something really custom is going on, e.g. subnet masks etc, in which case a miss for the default is totally fine since it's an advanced user who will know he needs to configure the extension via the settings)
2. which API route is the best to confirm connection? Is it `/api`?
3. The above lead me to ask, shouldn't the suffix `/api` be part of the user-supplied config value validation? I'm referring to the pattern `$protocol://$host:$port/$path` in the issue description, and us ensuring that the string ends in `/api` e.g. `/[blahblah]\/api$/g`

**Comment by gsaslis** [comment]
3. no, the path is part of our own app's compatibility with the API backend. 
2. https://github.com/cytechmobile/radicle-jetbrains-plugin/blob/main/src/main/java/network/radicle/jetbrains/radiclejetbrainsplugin/providers/ProjectApi.java#L35 
1. `http://127.0.0.1:8080`

**Comment by maninak** [comment]
Result:

https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/2b946c17-db02-4c2a-aa5c-def1d74dee4f
