### ISSUE TITLE
`RAD_HOME` setting and auth foundation

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#28]
We should add another input field in the Radicle settings.

The label should read: "Path to Radicle Node storage (`RAD_HOME`)"

(This is the path that heartwood uses for storage)

A **Test** button can be added that will work like this:

1. it runs `rad self` to check whether the specific path has already been set up
(this is some sample output with a new storage path)
```bash
23-05-19 16:32 ➜  heartwood git:(master) ✗ export RAD_HOME=~/.radicle_404
23-05-19 16:33 ➜  heartwood git:(master) ✗ rad self
✗ Self failed: Could not load radicle profile
✗ Hint: To setup your radicle profile, run `rad auth`.
```
1a. if path **hasn't** been set up, it asks the user if they want to create a new identity
  * it asks for the passphrase
  * it creates a new profile in the path, with `RAD_PASSPHRASE=<> rad auth` (or `rad auth --stdin` depending on what is the recommended way in VS Code to pass in a secret without exposing its value in the logs), and we show the user the did that was created and stop here. 

1b. if the path **has** been set up (`rad self` does return a did)

2. we need to check if `rad auth` is already set up: 

```bash
$ rad auth
✓ Signing key already in ssh-agent    
```

Caveat: `rad auth` switches to interactive mode to ask for the key passphrase in case it hasn't already been added, so this needs to run with a timeout to avoid blocking the UI. 

2a. if `rad auth` returned `Signing key already in ssh-agent`, we can tell the user that the path is ok and shows the DID of the identity that is found in that path (shown with command `rad self`).
2b. if `rad auth` hanged, we need to ask for a passphrase (similar to how we do when creating a new profile) and then provide that to `rad auth --stdin` or `RAD_PASSPHRASE=... rad auth` 

Note about "test" button: this is a common pattern in Jetbrains IDEs - perhaps there is something else that's similar in VS Code. 

**Related:**

- https://radicle.zulipchat.com/#narrow/stream/381750-ide-plugins-internal/topic/rad_home.20.22test.22.20button

**Comment by maninak** [comment]
@gsaslis do we want to store the user-provided passphrase for future reference? I remember you mentioning it but I noticed that it's not part of this ticket's spec.

But also on second thought, this seems like a bigger topic because:

- The provided native [SecretStorage API](https://code.visualstudio.com/api/references/vscode-api#SecretStorage) doesn't seem to be syncing across VS Code instances. If that's true, then this negates at least some of the benefit of the extension persisting the passphrase.
- If there's need to support multiple identities under different DID keys and thus different passwords as a result, then we may need to thing a bit more about the UX here.

**Comment by gsaslis** [comment]
a. We don't want to sync across instances. The key that the passphrase unlocks is only on one machine anyway. 

b. Regarding multiple identities- there's only one identity per `RAD_HOME`. ;)

**Comment by maninak** [comment]
What about the main question, do we want to (securely) store the passphrase? As part of this ticket or a new one?

**Comment by maninak** [comment]
In the ticket description the term "storage path" or "node storage" or related is used to describe what the env var `RAD_HOME` represents.

But given the contents of a valid `RAD_HOME` dir, e.g.:

- bin/
- keys/
- node/
- storage/ <-- especially due to this one, but not only

and the naming pattern used in the output of `rad self`, e.g.:

- Storage (git)  /home/maninak/.radicle/storage
- Storage (keys) /home/maninak/.radicle/keys

, I therefore concluded that the term Radicle storage relates to the subfolder of what `RAD_HOME` represents and referring to that as "node storage" etc would overload that term and be confusing to users.

Therefore in my implementation I'm going for the alternative (tentative, as of writing this) term "Path to Radicle node home directory" when describing `RAD_HOME` (the env var name kinda gives it away too).

**Comment by gsaslis** [comment]
@maninak this is probably a better question for the Heartwood team, because it still sounds to me like `RAD_HOME` == "Node Storage". 

* `Storage (git) /home/maninak/.radicle/storage` => can also be read as "the node storage path where git repos are stored"
* `Storage (Keys) /home/maninak/.radicle/keys` => can also be read as "the node storage path where keys are stored"

There are certainly terminology improvements we can make along the way, but I'm not yet convinced this is one such case.

**Comment by maninak** [comment]
Demo showcasing some of the above

https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/d6bdf8eb-6c55-46cd-b30b-181fc398f818
