### ISSUE TITLE
Add "Clone from Radicle" functionality to VS Code command palette

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#29]
Similar to how "Clone from GitHub" works, as shown in the screenshot below: 

![Image](https://user-images.githubusercontent.com/2420882/228803480-6958df6e-1775-46ea-9573-cb3dc18bab0c.png)

## Acceptance Tests: 

* In the command palette, I should see a "Clone from Radicle" option, as well as the "Clone from GitHub" option.
* After clicking "Clone from Radicle", I should see a loading bar, while the extension fetches projects from the Radicle node HTTP API
* After the extension loads the list of projects (from `/api/v1/projects/` ), I should see a list like the one shown in the screenshot, with the following differences
  * no star count
  * a rad icon, instead of a github icon
  * the radicle project name **in bold**
    * no namespace right now (we will add more functionality around peers and peer aliases in a future version of the plugin)
  * the radicle project description in the line below the name. 
    * if the description exceeds 80 chars, it should be shortened with a trailing `...` 
* After I click on a radicle project to clone, I should see the file picker, where I can select the destination directory where the project will be cloned.

**Comment by gsaslis** [comment]
I'm removing the `needs refinement` label and adding this to "Up Next". Please let me know if there are still open questions.

**Comment by maninak** [comment]
@gsaslis

I have bad news. This whole approach of extending the built-in Git -> Clone view has been leading us to a dead-end. That is because, as it says on the tin, this will only ever `git clone` and there's not way to overload the action on repo selection to instead `rad clone`. Moreover the former takes a URL param, while the latter takes a RID and `/projects` of httpd does not provide any URLs per radicle project anyway.

This fact affects both this present ticket and #27.

If Radicle were to ever integrate the side-effects of `rad clone` into `git clone` similarly to how `rad push` got integrated into `git push` etc, then we can potentially revisit this.

For the time being the good news is that there is a solid alternative. We can create a new VS Code command (available in the command palette) that offers a very similar (maybe even identical) UX as the built-in git clone command does.

Given the time constraints, I'll start working on this straight away unless instructed otherwise. Regarding the two tickets, I don't know if they should be updated or closed and replaced by (a) new (and perhaps merged?) one(s).

**Comment by gsaslis** [comment]
thanks for the update! 

> If Radicle were to ever integrate the side-effects of rad clone into git clone similarly to how rad push got integrated into git push etc, then we can potentially revisit this.

ok, something to look out for in the future. 
In the meantime, let's proceed without waiting for that. 

> We can create a new VS Code command (available in the command palette) that offers a very similar (maybe even identical) UX as the built-in git clone command does.

sounds like the definite way forward. Thanks for starting to head that way already! 👍🏼

**Comment by gsaslis** [comment]
@maninak I’ve updated title + desc after our chat this morning. thanks for the explanation.

**Comment by maninak** [comment]
Result:

- new command `radicle.clone` available in the VS Code's Command Palette
- list with all tracked repos (adheres to extension's `RAD_HOME` configuration) detailing
	- project name
	- project ID (RID)
	- project description
	- count of other nodes tracking the project (when available)
- filter listed projects by
	- name
	- RID
	- description
- hint that `radicle-httpd` needs to be up if the connection failed
- offer to open the successfully cloned repo in a new vscode window with a single click
- list rad clone command in the native Source Control three-dot-menu's Radicle submenu
    ![image](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/7125130f-3fd4-438d-9640-428160d48488)
- when opening VS Code without any folder in the workspace show in the dedicated Welcome View an additional button to clone from Radicle
    ![image](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/eacdc525-07d2-494b-9bff-545e5c8eb3c9)

_(demo video soon)_
