### ISSUE TITLE
Get Started Link Broken

### ISSUE THREAD

**Issue by bordumb** [cytechmobile/radicle-vscode-extension#31]
## Issue

This was working the other day, but I think due to the rebranding, the "Getting Started" link has since broken

<img width="476" alt="image" src="https://user-images.githubusercontent.com/3743841/233413891-2d27d7a5-a0e8-4a03-9761-e0a69580b0e7.png">

The current link goes here:
https://radicle.xyz/get-started.html

But is now pointing to a broken page:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/3743841/233414077-9b62eecd-a282-4016-943d-7a3e760fded2.png">

## Proposal

I'd try and find an alternative

And make a note to the Radicle team about making a permanent/canonical getting started page that won't break

These types of pages tend to be linked externally a lot

**Comment by maninak** [comment]
Hey @bordumb, thank you for creating an issue for this topic! :raised_hands: 

In truth, we've been aware of this broken link --as well as other inconsistencies, including branding discrepancies emergent from the Radicle rebranding-- since the very first day the new website was published but hadn't documented them in issues yet (Easter time).

I'll see if I can sort all that out today. I'll keep you posted. :)

**Comment by maninak** [comment]
Here's the [discussion](https://radicle.zulipchat.com/#narrow/stream/369278-web/topic/.E2.9C.94.20dedicated-getting-started-url/near/352339216) with the team and the follow-up.

- the page doesn't under the URL [radicle.xyz/get-started.html](https://radicle.xyz/get-started.html) exist anymore and there are no plans to restore it.
- the previously broken link will now be "fixed"/mitigated for us (VS Code extension) and everyone else by having it at least redirect to the home page
- the CLI team has a getting-started flow planned for the CLI itself
