### ISSUE TITLE
Add troubleshooting flow for HTTP API endpoint

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#37]
When the user inserts an incorrect API endpoint in the extension settings, we can take that opportunity to guide them towards the right value with a troubleshooting dialog.

**Comment by maninak** [comment]
We already have this https://github.com/cytechmobile/radicle-vscode-extension/blob/main/src/ux/httpdConnection.ts#L55-L83

![image](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/2725f61d-c546-4ed2-b56a-88c3b885a682)


which was done as part of https://github.com/cytechmobile/radicle-vscode-extension/issues/39#issuecomment-1696969368

If that's sufficient please close the issue, otherwise, we need to define specific ACs.
