### ISSUE TITLE
Show list of Radicle Patches in Radicle extension panel

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#43]
This issue is about creating the first container that will hold the list of Radicle Patches, within the Radicle extension panel. 

In an attempt to create a similar-to-github experience (in order to make migration to radicle less painful), we can use the GitHub extension for inspiration in our design. 

With that in mind, this issue is about the top section ("Pull Requests" in the case of GH extension), as shown in the screenshot below. 

![Image](https://github.com/cytechmobile/radicle-vscode-extension/assets/2420882/0a4982f6-8e45-4c00-aab2-e50e359d6d06)

In scope for this particular issue, we have only the following: 

* listing all patches (with no filters) returned by the HTTP API
* the patch list item should show: 
  * the alias of the author
  * the title of the patch
  * the patch ID

Out of scope (for now):

* configurable queries
* creating new Patch
* expanding a patch to view files, etc. 
* the patch overview page (viewable when clicking on "Description")
* changing the state of a patch

**Comment by gsaslis** [comment]
@maninak please take a look and let me know what else we should clarify

**Comment by maninak** [comment]
> @maninak please take a look and let me know what else we should clarify

There's nothing I've thought of as of this point. I won't be surprised if some questions come up while working on this. In that case, I'll just reach out, as always. :)

**Comment by maninak** [comment]
**Results:**

- new Patches view lists all patches of all statuses
    ![patches](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/468bc650-caaf-49d3-b919-373b85038061)
  - view will only be shown if repo is rad-initialized
  - each item shows revision title, relative time since latest revision, author of latest revision, abbreviated hash of patchId
  - list items are sorted by patch status (first sorting level) and subsequently by latest revision date (most recent first)
- indicates to the user when no patches were found or a request failed
    ![no-patches-found](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/e5ae3db7-2cfd-4569-889e-3e44872280c7)
    ![partial-fetch-error](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/96df6f0a-a592-453d-b2f9-fe580282455d)
- loading indicator is shown while fetching and preparing to render items
- a button to refresh the list of patches is shown on hover of the Patches view title
- a command to refresh the list of patches is added to VS Code's Command Palette
    ![command-refresh-patches-list](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/2b255b29-ebc7-4367-a55d-452fdbe21a09)
- a button to copy the patch id to clipboard is shown on list-item hover
- an option to copy the patch id to clipboard is shown on list-item right click
- when the http api endpoint config in the settings changes the patches automatically re-fetched (and the view re-renders accordingly)
- on list item hover, a tooltip with plenty more info is shown
  - tooltip supports HTML too
  - any html gets sanitized for security before rendered ([see allowed tags](https://github.com/microsoft/vscode/blob/6d2920473c6f13759c978dd89104c4270a83422d/src/vs/base/browser/markdownRenderer.ts#L296)).
  - will additionally show "Last Revised by ${alias} on ${date}" if there are more than one revisions
  - shows localized datetime format including relative "time ago" (e.g. 2 days ago)
  - patch status is denoted by dedicated icon _and_ color (relying only on color to convey info is bad UX!)
- improve copy of http-connection-error notification's button
- when opening the Settings UI focused at a specific config, the correct scope, `User` or `Workspace`, will be automatically selected based on which is actually being evaluated as the result.
- make available options during onboarding's troubleshooting flow easier to select at a glance
- further refinements of httpd client architecture given expanded context
- readme and changelog updated for all the above
