### ISSUE TITLE
Expand Patch item to show sublist of changed files (changeset)

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#46]
The list of changed files can be shown as an expandable section, under the Radicle Patch title. 

Upon selecting a file on the left, the diff of the file should be shown on the main editor (as a new tab), thus presenting a nice way to easily switch between changes in different files. 

For bonus points, each file can have a checkbox next to it (just like in the screenshots below) that is used to indicate that a file has been "viewed". This is useful in larger PRs where reviewers need some way to keep track of the files they have already reviewed. 

![Image](https://github.com/cytechmobile/radicle-vscode-extension/assets/2420882/a1a62d55-8425-44b9-ab3c-5670a5d987f1)

 

![Image](https://github.com/cytechmobile/radicle-vscode-extension/assets/2420882/6eb2d313-6370-4a3d-8741-80327f5b53d5)

## Out of scope 

We will keep the inline commenting functionality of the diff viewer out of scope for this particular issue and add it in the future in a separate issue, as required.

**Comment by gsaslis** [comment]
@maninak please let me know what you think about the approach above

**Comment by maninak** [comment]
@gsaslis could you please share an example httpd rewest to mark a hunk and/or file as `viewed` in patches? Or will this be a client-side-only feature (not supported by the radicle network's patches)?

**Comment by gsaslis** [comment]
Client-side only ;)

**Comment by maninak** [comment]
@gsaslis I assume that the list of changed files represents the state of the most recent Revision of the Patch, correct?

**Comment by gsaslis** [comment]
That's correct, yes. 👌

**Comment by maninak** [comment]
**Result:**

![patches-diff](https://github.com/cytechmobile/radicle-vscode-extension/assets/7542054/57c750a3-7a05-4fd2-a275-25b9a44af8b3)

- each Patch item in the Patches view can now be expanded
  - shows a sub-list of the files changed in the latest Revision of that Patch when compared to the Revision base commit
  - the files are sorted by directory first and then by filename
  - a hint to the user as to why there are no filechanges, if that's the case
- each filechange item in the list
  - shows the filename
  - shows the path to the filename if that Patch contains multiple changed files with the same name
  - automatically uses the File Icon matching that file according to the user's selected File Icon Theme set in VS Code settings (if any)
- on filechange item hover a tooltip is shown
  - with the relative path starting from project root (including the filename)
  - with the kind of change that this file had (e.g. `added`, `modified`, `moved`, etc)
  - if the file was `moved` or `copied` then both the `oldPath` and `newPath` are shown with an arrow between them
- on filechange item left-click an editor opens showing the diff between the file's version in the latest revision of that Patch and the version in that revision's base.
- on filechange item right-click the context menu has
  - a command to "Open Original Version" available only to items with filechange kinds "deleted" or "modified"
  - a command to "Open Changed Version" available only to items with filechange kinds "added" or "modified"
- the Patches view title-bar has a new "Collapse All Items in Patches View" button to the right of the refresh button
- the Command Palette has a new command to "Collapse All Items in Patches View"
- copy of all commands is now (consistently) in Title Case as per the VS Code UX Guidelines

Marking the changed files as viewed isn't done as it requires _significant_ amount of work, but IMO we should definitely work on it in the scope of a new dedicated ticket.

**Comment by maninak** [comment]
In the interest of time I'm dumping here notes about things that IMO should be done too (as separate tickets)

- TODO: maninak update readme and changelog regarding file diff
- TODO: maninak check what happens when diffing non-text file like images
- TODO: maninak as first treeItem if an expanded patch show files changed `+${A} ~${M} -${D}` (colored) and/or lines changed
- TODO: maninak show lines added | removed on changefile item tooltip
- TODO: maninak show M or A or D (colored!) at the right-most side of each file treeitem signifying modified, added or deleted
- TODO: maninak add checkbox next to each item which on hover shows tooltip "Mark file as viewed". A check should be keyed to each `revision.id+file.resolvedPath`. Sync state across vscode instances. Add a config to toggle showing it.
- TODO: maninak prefix each Patch item description with `✓` (or put on the far right as icon) if branch is checked out and in tooltip with `(✓ Current Branch)`.
- TODO: maninak open the diff editor using the actual path and in unchangeable read-only (opening a diff of an old commit via the native git plugin shows "Editor is read-only because the file system of the file is read-only." which means we could perhaps have the files in-memory instead of using temp files??! Maybe this is related https://github.com/microsoft/vscode-extension-samples/tree/69333818a412353487f0f445a80a36dcb7b6c2ab/source-control-sample or maybe a URI with custom scheme https://code.visualstudio.com/api/extension-guides/virtual-documents#textdocumentcontentprovider) or by making a Repository https://stackoverflow.com/questions/54952188/showing-differences-from-vs-code-source-control-extension/54986747#54986747
- TODO: maninak show Gravatar or stable randomly generated avatar (use the one from `radilce-interface`) on Patch list item tooltip. Prefix PR name with status e.g. `Draft •` or `[Draft]`. Add a new `radicle.patches.icon` config with options [`Status icon`, `Gr(avatar)`, `None`] https://github.com/microsoft/vscode-pull-request-github/blob/d53cc2e3f22d47cc009a686dc56f1827dda4e897/src/view/treeNodes/pullRequestNode.ts#L315
- TODO: maninak make a new ticket to create a new expandable level of all Revisions inside a Patch and outside the files list. Expanding the Patch should auto-expand the most recent revision. Expanding a revision should collapse all other revisions of a Patch. On right-click there should be an option to "Open Diff since Revision..." and show a list of all revisions of this Patch for the user to select one. On selection open diff with that as base On right-click there should be an option to "Open Changes since Commit..." and show a selection list of all commits on that revisions up until one marked "base". On selection open diff with that as base. If both of the above are implemented, then make a sublist "Open Changes since" with the above as sub-items.

**Comment by gsaslis** [comment]
@maninak I may have missed it, but one `TODO` here still is the checkbox feature, right?

> each file can have a checkbox next to it (just like in the screenshots below) that is used to indicate that a file has been "viewed". This is useful in larger PRs where reviewers need some way to keep track of the files they have already reviewed.

**Comment by maninak** [comment]
It's actually in my list (copy-pasta)

> TODO: maninak add checkbox next to each item which on hover shows tooltip "Mark file as viewed". A check should be keyed to each revision.id+file.resolvedPath. Sync state across vscode instances. Add a config to toggle showing it.

I understand those TODO notes (pulled directly from my source) can be quite cryptic, but if you create an issue tagged as `needs-refinement` and assign it to me, I'll clean it up.

The context behind many of those is that adding "decorations" (anything other than icon on the left, title, and description) in `TreeViewItem`s requires some quite tricky work, including fiddling with sparsely documented APIs I need to reverse-engineer by seeing how they are used in other extensions, which I tried to do and failed in my first timeboxed attempt.

With what I've seen until now though, I have the impression that figuring out and setting up that foundational tech layer unlocks the ability to greatly extend our UI capabilities and some opportunities for stellar UX.

**Comment by gsaslis** [comment]
issue created: https://github.com/cytechmobile/radicle-vscode-extension/issues/93
