### ISSUE TITLE
Extension incorrectly determines whether a project is a radicle project

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#59]
I cloned heartwood and then opened the project in vs code and when I open the Radicle pane , I see that the project is not recognized as a Radicle project.

**Comment by maninak** [comment]
It's not clear from the description what is actually shown. I understand that the expected view would be the one with the push/pull/sync buttons.

I'll make the assumption that you're referring to the Welcome View saying "The git repository currently opened in your workspace is not yet initialized with Radicle.". That view is configured to be shown when: `workspaceFolderCount > 0 && gitOpenRepositoryCount > 0 && !radicle.isRadInitialized`

The two former when-clause-context vars are implemented from vscode itself, the latter one, obviously from us.

This is the implementation of how we get the value for `radicle.isRadInitialized`:

```ts
/**
 * Answers whether the currently open workspace folder contains a Radicle initialized
 * git repository.
 *
 * @returns `true` if the workspace is a rad-initialized repo, otherwise `false`.
 */
export function isRadInitialized(): boolean {
  const isInitialized = Boolean(exec(`${getRadCliRef()} inspect`, { cwd: '$workspaceDir' }))

  return isInitialized
}
```

Source: https://github.com/cytechmobile/radicle-vscode-extension/blob/de91376655a60030f86f07e2129f5e302c44abf9/src/helpers/radCli.ts#L77C1-L87C2

@gsaslis,
1. is running `rad inspect` still the correct heuristic to detect whether a repo is rad-initialized?
2. is it safe to assume that a rad-cloned project is always rad-initialized?

If the answer to both above questions is `yes`, then (we have the correct approach but buggy implementation and) I should debug if and why `radicle.isRadInitialized` isn't getting the correct value.

Otherwise, we must rethink our heuristic checks and adjust the logic (and perhaps the welcome view copy) accordingly. In that case, I would need the new specs from you.

**Comment by gsaslis** [comment]
> is running rad inspect still the correct heuristic to detect whether a repo is rad-initialized?
yes
> is it safe to assume that a rad-cloned project is always rad-initialized?
yes

Here is a screenshot:

![Screenshot 2023-07-17 at 9 25 54 AM](https://github.com/cytechmobile/radicle-vscode-extension/assets/2420882/dd075bce-6e69-400d-b3df-f68122d96c11)

So, yes, it looks like we do have the correct approach and some bug in our implementation. 

here is the repo I tested with: https://app.radicle.xyz/seeds/radicle.yorgos.net.gr/rad:z3FWyQNsqKXLkGvN6bQjJR4UoBBEq

**Comment by maninak** [comment]
Which extension version are you using? Can you confirm you're using the latest one `0.2.1`?
https://marketplace.visualstudio.com/items?itemName=radicle-ide-plugins-team.radicle&ssr=false#version-history

**Comment by gsaslis** [comment]
ok, this is weird. seems I can't install that version 🤔 

![Screenshot 2023-07-17 at 10 12 24 AM](https://github.com/cytechmobile/radicle-vscode-extension/assets/2420882/14632abe-1321-4de8-9e23-f4c9cd295e8d)

**Comment by maninak** [comment]
Interesting. I'm pretty sure that VS Code auto-updated to the latest version for me when `0.2.1` was published. Uninstall and re-install to see if this bug is resolved for you.

**Comment by gsaslis** [comment]
ok it looks like I needed to **first upgrade VS Code** itself and then I was able to update to the latest version of the extension. It all works now. 

Maybe worth documenting the VS Code version somewhere?

**Comment by maninak** [comment]
Aha, this could be a result of bumping the vscode version requirement defined in `engines`:

https://github.com/cytechmobile/radicle-vscode-extension/commit/3d1fe6fa80b461c6ebc36eaff74524bb47eecac5#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R21

We could start documenting this, but I've never seen anyone do it. Updates are free, backward compatible and come at regular intervals, so the vast majority auto-update.

The action item I get from this is that we should perhaps define bug templates (github specific), so that reporters include extension version as a reporting step.
