### ISSUE TITLE
Support posting general comments

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#78]
This issue is about the ability to add general comments to the radicle patch, through a dedicated textarea at the bottom of the Activity / Overview page that opens in the vs code editor.  

![Image](https://github.com/cytechmobile/radicle-vscode-extension/assets/2420882/f6d75b5e-ad50-4e8d-8087-b23454462cfb)

**Comment by gsaslis** [comment]
@stelios123 could you please help here by providing the API endpoints used for this functionality ?

**Comment by Stelios123** [comment]
The API endpoint will change based on this [conversation ](https://radicle.zulipchat.com/#narrow/stream/383670-patches/topic/httpd.3A.20Add.20reactions.20to.20patch.20revisions).

Currently for reactions we are using this endpoint for patches `/api/v1/projects/<PROJECT_ID>/patches/<PATCHES_ID>`
This is a PATCH request with this parameters
```
{
"type" : "revision.comment.react",
"revision" : "REVISION_ID",
"comment" : "COMMENT_ID",
"reaction" : "EMOJI UNICODE",
"active" : true / false
}
```
Based on active variable you can add / remove emoji

For issues we are using `/api/v1/projects/<PROJECT_ID>/issues/<ISSUE_ID>`. This is also a PATCH REQUEST
and the parameters

{
"type" : "comment.react",
"id": "DISCUSSION_ID",
"reaction" : "EMOJI UNICODE",
"active" : true / false
}

Our code : [Patch comment react](https://github.com/cytechmobile/radicle-jetbrains-plugin/blob/c81949c4e934e963ba4d4c41473b7255a4388af7/src/main/java/network/radicle/jetbrains/radiclejetbrainsplugin/services/RadicleProjectApi.java#L424)
[Issue comment react](https://github.com/cytechmobile/radicle-jetbrains-plugin/blob/c81949c4e934e963ba4d4c41473b7255a4388af7/src/main/java/network/radicle/jetbrains/radiclejetbrainsplugin/services/RadicleProjectApi.java#L448)

**Comment by maninak** [comment]
This got a bit out of hand and brings, due to hastiness, plenty of related features/fixes in the same PR, though some could have been part of separate PRs. Alas.

**Demo:**

![image](https://github.com/user-attachments/assets/a2ff2627-5807-4257-a28a-fdeb01c67085)

**Changelog:**

### ✨ Highlights

- create new comments on patches
- preview your patch edits and draft new comments, before submitting them, with Markdown support
- polished, comfortable authoring experience

### 🚀 Enhancements

- **patch-detail:** add a new "Comment" button next to the revision selector
  - clicking the button shows a new patch-comment form in the top of the Activity section
    - the form consists of
      - a text-field where the user can type their comment
      - the target revision under which the comment is to be created
      - form control buttons
    - if in single-column mode due to narrow viewport the active tab automatically switches to the Activity section
    - form state is preserved (as described in [v0.5.0#enhancements](#v050-july-22nd-2024)) individually for each revision
  - clicking the form's "Comment" button or the keyboard shortcut `Ctrl/Cmd + Enter` submits the form
    - attempts to create a new comment on radicle under the selected revision
    - informs the user of the action's result (created and announced / created only locally / failed) and offers follow-up actions as needed
    - upon the comment's successful creation, it is shown directly in place of the patch-comment form as a new event at the top of the Activity section with the time-ago indicator showing "now" and a short "pulse-outline" animation around it
- **patch-detail:** in the patch-edit form
  - show placeholder text when either text-field is empty
  - change button label "Save" to "Update"
- **patch-detail:** in both patch-comment and patch-edit forms
  - add a new button with a coffee icon between "Update"/"Comment" and "Discard"
    - clicking it "pauses" editing, hiding the form but preserving the current changes for later (a.k.a. aforementioned form state preservation)
    - also triggerable with keyboard shortcut `Escape`
    - also acts as a safe "spacer" between the two aforementioned buttons protecting against misclicks that would otherwise come with a big penalty
  - add a new button to toggle a markdown preview of the current changes before submitting
    - also triggerable with keyboard shortcut `Alt + P`
    - after toggling to markdown preview and back to editing the undo/redo history (Ctrl/Cmd + Z and Ctrl/Cmd + Shift + Z) is still available. Even if the form contains multiple controls (e.g. two text-areas) then the undo/redo history spanning _all of them in the order they were changed_ is still retained
  - polish text-field sizing dynamics:
    - use 1 line of text as starting height when empty for the patch title field and 4 lines for the patch description
    - respectively limit the max vertical lines for the former and the latter
    - fields offer 65 characters of horizontal space (when there's enough viewport width, whatever fits otherwise), which also happens to be the Markdown renderer's wrapping limit (with exceptions). This can double as a subtle hint that we may be typing too much. Longer lines of text widen the fields to fit the content as long as there's enough viewport space, at which point they'll wrap into a new line, line-breaking at at appropriate point.
    - previously typing or focusing any of the form's fields would always scroll the viewport to align the form at its bottom. Now this happens only if the form doesn't already fit on the viewport, leaving the scroll position wherever it was already set by the user and resulting in a less constricting experience
    - although fields remain manually user-resizeable (pursposefully only across height) by mouse-dragging the bottom-right handle of each field _and_ dynamically resizeable as content grows (with contextual restrictions) and shrinks, if the user indeed defines a preferred height using the former method, then it is respected by the latter
  - the aforementioned coupled with the pre-existing feature of optimally auto-aligning the form as it resizes should seamlessly provide a smooth authoring experience
  - adjust the hover text of all form buttons to advertise their respective keyboard shortcut (if any)
  - **patch-detail:** preselect the merged revision, if any, in the revision selector instead of always the latest
  - **patch-detail:** don't mention the revision and its identifier in events in the Activity section if there's only one revision
  - **patch-detail:** align the UX for every revision identifier shown in the patch-major-events section (top of the view) with the behaviour of those in the Activity section, i.e. showing the revision description on hover, and when clicked scrolling to the Revision section wherin more info about it is shown
  - **patch-detail:** don't mention the related commit in the patch-major-events section (~~"Last updated by W with revision X at commit Y Z time ago"~~). This information is still available in the Revision section.
  - **patch-detail:** keep the labels of the main buttons (top-right of the view) as a single line of text, even if the viewport is narrow enough to compress them
  - **patch-detail:** add themed styling to `<summary>` elements when tabbed into

### 🩹 Fixes

- **patch-detail:** don't disappear the Activity and Revision sections sometimes, e.g. when a new revision is detected
- **patch-detail:** make "Refresh" button work again, fetching latest patch data
- **patch-detail:** don't show big gap between patch title and next section if the patch description is empty

### 🏡 Chores

- **ts:** enforce stricter type-checking for webview apps
- **deps:** upgrade webview app dependencies, including latest Vue v3.5

**Comment by maninak** [comment]
This got a bit out of hand and brings, due to hastiness, plenty of related features/fixes in the same PR, though some could have been part of separate PRs. Alas.

**Demo:**

![image](https://github.com/user-attachments/assets/a2ff2627-5807-4257-a28a-fdeb01c67085)

**Changelog:**

### ✨ Highlights

- create new comments on patches
- preview your patch edits and draft new comments, before submitting them, with Markdown support
- polished, comfortable authoring experience

### 🚀 Enhancements

- **patch-detail:** add a new "Comment" button next to the revision selector
  - clicking the button shows a new patch-comment form in the top of the Activity section
    - the form consists of
      - a text-field where the user can type their comment
      - the target revision under which the comment is to be created
      - form control buttons
    - if in single-column mode due to narrow viewport the active tab automatically switches to the Activity section
    - form state is preserved (as described in [v0.5.0#enhancements](#v050-july-22nd-2024)) individually for each revision
  - clicking the form's "Comment" button or the keyboard shortcut `Ctrl/Cmd + Enter` submits the form
    - attempts to create a new comment on radicle under the selected revision
    - informs the user of the action's result (created and announced / created only locally / failed) and offers follow-up actions as needed
    - upon the comment's successful creation, it is shown directly in place of the patch-comment form as a new event at the top of the Activity section with the time-ago indicator showing "now" and a short "pulse-outline" animation around it
- **patch-detail:** in the patch-edit form
  - show placeholder text when either text-field is empty
  - change button label "Save" to "Update"
- **patch-detail:** in both patch-comment and patch-edit forms
  - add a new button with a coffee icon between "Update"/"Comment" and "Discard"
    - clicking it "pauses" editing, hiding the form but preserving the current changes for later (a.k.a. aforementioned form state preservation)
    - also triggerable with keyboard shortcut `Escape`
    - also acts as a safe "spacer" between the two aforementioned buttons protecting against misclicks that would otherwise come with a big penalty
  - add a new button to toggle a markdown preview of the current changes before submitting
    - also triggerable with keyboard shortcut `Alt + P`
    - after toggling to markdown preview and back to editing the undo/redo history (Ctrl/Cmd + Z and Ctrl/Cmd + Shift + Z) is still available. Even if the form contains multiple controls (e.g. two text-areas) then the undo/redo history spanning _all of them in the order they were changed_ is still retained
  - polish text-field sizing dynamics:
    - use 1 line of text as starting height when empty for the patch title field and 4 lines for the patch description
    - respectively limit the max vertical lines for the former and the latter
    - fields offer 65 characters of horizontal space (when there's enough viewport width, whatever fits otherwise), which also happens to be the Markdown renderer's wrapping limit (with exceptions). This can double as a subtle hint that we may be typing too much. Longer lines of text widen the fields to fit the content as long as there's enough viewport space, at which point they'll wrap into a new line, line-breaking at at appropriate point.
    - previously typing or focusing any of the form's fields would always scroll the viewport to align the form at its bottom. Now this happens only if the form doesn't already fit on the viewport, leaving the scroll position wherever it was already set by the user and resulting in a less constricting experience
    - although fields remain manually user-resizeable (pursposefully only across height) by mouse-dragging the bottom-right handle of each field _and_ dynamically resizeable as content grows (with contextual restrictions) and shrinks, if the user indeed defines a preferred height using the former method, then it is respected by the latter
  - the aforementioned coupled with the pre-existing feature of optimally auto-aligning the form as it resizes should seamlessly provide a smooth authoring experience
  - adjust the hover text of all form buttons to advertise their respective keyboard shortcut (if any)
  - **patch-detail:** preselect the merged revision, if any, in the revision selector instead of always the latest
  - **patch-detail:** don't mention the revision and its identifier in events in the Activity section if there's only one revision
  - **patch-detail:** align the UX for every revision identifier shown in the patch-major-events section (top of the view) with the behaviour of those in the Activity section, i.e. showing the revision description on hover, and when clicked scrolling to the Revision section wherin more info about it is shown
  - **patch-detail:** don't mention the related commit in the patch-major-events section (~~"Last updated by W with revision X at commit Y Z time ago"~~). This information is still available in the Revision section.
  - **patch-detail:** keep the labels of the main buttons (top-right of the view) as a single line of text, even if the viewport is narrow enough to compress them
  - **patch-detail:** add themed styling to `<summary>` elements when tabbed into

### 🩹 Fixes

- **patch-detail:** don't disappear the Activity and Revision sections sometimes, e.g. when a new revision is detected
- **patch-detail:** make "Refresh" button work again, fetching latest patch data
- **patch-detail:** don't show big gap between patch title and next section if the patch description is empty

### 🏡 Chores

- **ts:** enforce stricter type-checking for webview apps
- **deps:** upgrade webview app dependencies, including latest Vue v3.5
