### ISSUE TITLE
Extension pollutes recently opened files

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#94]
User input:

> After a time all the files that I open during review are left in the recently opened files under some application path /var/folders/...
So I'm thinking would it be possible for a vscode extension to clean up after itself those files?

> It's possible to clean up manually, just thinking it would be nice if the extension could do it by itself

**Comment by sebastinez** [comment]
Here a picture for reference

![image](https://github.com/cytechmobile/radicle-vscode-extension/assets/7912302/0cd6cbb4-f21d-4dea-9c25-9c35849ef045)

**Comment by gsaslis** [comment]
Relevant discussion on zulip: https://radicle.zulipchat.com/#narrow/stream/380896-ide-plugins/topic/extension.20pollutes.20recently.20opened.20files/near/398686609

Workaround exists!

> Ok was able to assign a hotkey to remove all recently opened files which makes it easier.
And it seems vscode is working on being able to exclude paths from recently opened files
https://github.com/microsoft/vscode/issues/157395

**Comment by maninak** [comment]
It seems that none of the workarounds are effective. We likely need to figure out how to do the "in-memory" diffing which requires tricky reverse engineering from other extensions, but it will be worth it in the end if we crack it.

**Comment by maninak** [comment]
Oh wow, this came up and looks promising!!

https://github.com/microsoft/vscode/issues/157395#issuecomment-2079870251

**Comment by maninak** [comment]
For anyone following this, **please upvote** this related [issue in the vscode repo](https://github.com/microsoft/vscode/issues/211438) ASAP to get MS to look at it.

**Comment by maninak** [comment]
I implemented a new config `excludeTempFilesFromRecentlyOpened` in the extension's settings with default `true`, which updates the user's vscode config `search.exclude` with a new entry to ignore all files under e.g. for Linux `/tmp/radicle/**`. 

It seems that this feature which was until now missing, is now _kinda_ there but still buggy and I reported it as such to [an issue](https://github.com/microsoft/vscode/issues/157395#issuecomment-2080293320) assigned to a maintainer.

I'll wrap up my forwards-compatible implementation and ship it in the next release. The feature will start working if/when this bug is patched in a new VS Code version. Until then it is inert.

I urge anyone reading this to also [please go upvote this related issue](https://github.com/microsoft/vscode/issues/211438) which needs to meet a minimum amount of upvotes until a deadline to be considered.

**Comment by maninak** [comment]
Good news, an MS staff engineer has accepted the bug report, added it to the May backlog and is assigned to the

**Comment by maninak** [comment]
After our (laborious) intervention the VS Code bug [is fixed](https://github.com/microsoft/vscode/commit/0ab35b5c760e42a59e9e7ae39e5e0db0ca401204#diff-9f3b3c22d9e1bbb7b80110962c4a3ec35624ae02090646217ce4643845f34e77R845) and should be published with their upcoming release beginning of May.

**Comment by sebastinez** [comment]
nice work @maninak kudos! 👏

**Comment by lorenzleutgeb** [comment]
If there are no temporary files, then they won't appear in the history, and we also won't need to hack around hiding them, see #128 for an implementation.

**Comment by maninak** [comment]
Yup, that's been planned to be tackled next. Thank you for already taking a stab at it, Lorenz! :raised_hands:

**Comment by maninak** [comment]
**Results:**

### 🚀 Enhancements

- **settings:** add config to toggle excluding temporary files created by the extension, e.g. those used to produce the diff of a patch's changed files, from the list of recently opened files. This is enabled by default. This currently works only partly, but should automatically be fully working when [the underlying VS Code bug](https://github.com/microsoft/vscode/issues/157395#issuecomment-2080293320) is fixed and released (ETA beginning of May).

**Comment by maninak** [comment]
As of the published stable version of VS Code [1.90](https://code.visualstudio.com/updates/v1_90) this solution is in effect.
