### ISSUE TITLE
Support renaming patch title

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-vscode-extension#97]
As a patch author, I should be able to rename my patch.

**Comment by maninak** [comment]
Due to needing things that needed things, since it's our first mutation, the work for this ended up becoming larger than expected. And there's still more complementary features to come but I opted to bring those as separate additional PRs.

**Results:**

### 🚀 Enhancements

- **patch-detail:** support mutating patch titles and descriptions
  - a new "Edit" button has been added next to the title, shown when hovering on the title or description. Clicking it will show two text-areas, one for each of the aforementioned, and additional buttons
  - the Edit button:
    - is only available if the local identity is the author of the patch or among the repository's delegates
    - is able to be tabbed into with the keyboard, which will make it visible again, despite it being conditionally hidden (accessibility)
    - gets thinner on narrower viewports to allow maximum space for the already constricted title
  - while editing the following buttons are shown:
    - "Save" updates the changed title to Radicle
    - "Discard" stops the editing mode and discards the values currently entered in the text-area as well as the preserved drafts, if any (see below the functionality of Escape key)
    - their tabbing order (tabbing into them past the text-areas) is set so that "Save" is first, as expected in a form, despite them being right-aligned
  - the text-area:
    - supports any text content, including markdown and any special or uncommon characters
    - gets keyboard focus automatically when the edit button is clicked
    - auto-expands and auto-shrinks vertically to optimally fit its content, up to a viewport-relative maximum. Applies on focus and while typing.
    - keeps the viewport pinned at an optimal and stable scroll position regardless of how the text-area resizes
    - can be manually resized by dragging its bottom-right corner, but only vertically to keep the interaction less chaotic
    - has maximum and minimum height defined, after which internal scrolling of the contents is enabled
    - responds to viewport size changes applying sizing limits on top of the aforementioned content-relative resizing
    - is set with (generous) max char count limits to limit abuse
    - pressing the Enter key enters a new line but pressing Ctrl/Cmd+Enter behaves as if the "Save" button was clicked
  - the value of each text-area is auto-saved in memory as a draft while typing, as well as the "is editing" status of the form, and those will be attempted to be restored:
    - if the editor panel is hidden (another panel is selected placing it in the background) and then re-viewed (same session)
    - if VS Code is terminated or crashes (across sessions)
    - if the form submission fails
  - if Escape key is pressed editing stops. The current changes get stored as a draft that will be reused if editing is restarted during the same VS Code usage session
  - clicking "Save" executes a rad CLI command updating both the title and description from the form after trimming any leading and trailing whitespace
  - if the user is not authed when clicking "Save", the Authentication Flow is launched interstitially, upon the successful completion of which the patch edit command will follow
  - busy/progress indicator is shown in the Patches view while the patch-update command is executing
  - depending on the outcome of the patch edit command the user is presented with
    - an info notification that the patch was updated and the changes announced over the network. Those changes also immediately propagate across all UI elements of the extension and its webviews.
    - a warning notification that the patch was updated but only locally without the changes reaching the network. The user is offered the options to "Retry Announce" or "Show Output".
    - an error notification that the update failed altogether. The user is offered the option to "Show Output" and if the error was due to a timeout (either nodejs or rad CLI-based) they are also offered to "Retry With Longer Timeout".
      - if "Retry With Longer Timeout" is clicked, the patch edit command will be retried with a two minute timeout
      - each time a rad operation is launched with a timeout longer than 30s then its busy indicator is instead shown in the [Status Bar](https://code.visualstudio.com/docs/getstarted/userinterface), not the Patches view
      - each time the retried command with longer time-out also times out, then the user is again presented the "Retry With Longer Timeout" which will quadruple the previous timeout (e.g. 2, 8, 24 minutes etc)
- **patch-detail:** replace former "Reveal" button with a new "Browse Diff" one that still reveals the patch among others in the list but additionally expands it to show the changed files and moves the keyboard focus over to that item
- **patch-detail:** the former "Check Out Default" button now has a dynamic copy "Check Out $nameOfdefaultBranch"
- **exec:** invoke Radicle CLI binary directly for rad commands without spawning a shell
  - increased robustness by negating the extension's exposure to OS/shell-specific edge cases
  - lays much of the groundwork for the upcoming independence of the extension from the Radicle HTTP daemon for local operations
- **settings:** disallow usage of now unsupported relative paths for config `radicle.advanced.pathToRadBinary`
- **settings:** support trailing slashes for config `radicle.advanced.pathToNodeHome`

### 🔥 Performance

- **exec:** invoke Radicle CLI binary directly for rad commands to remove a 20-40ms overhead on rad commands which results in all-around speed-up of the extension including its activation time

### 🛡️ Security Fixes

- **exec:** sanitize untrusted paths and other values before interpolating them into shell commands or forgo spawning a shell altogether, massively enhancing protection against shell injection attacks

### 🩹 Fixes

- **store:** fix a couple dozens interconnected (:sigh:) state syncronization bugs between the Patch Detail view and the Patches view that each would occur only following very specific reproduction steps.
- **webview:** keep panel's title in sync with the title of the patch shown within it as it gets updated either from the extension user or from network users
- **patch-list:** let the "Updated X time ago" text in the title bar of the Patches view be updated when there's only one patch in the curently open repo and the user refetched its data exclusively, e.g. using the "Refresh" button in the Patch Detail view
- **markdown:** ensure the language tag on (recognised) code blocks is still shown after re-rendering them
- **markdown:** make the language tag on (recognised) code blocks not user-selectable
- **log:** show the actual output of failed rad commands (which explains _why_ it failed...) instead of sometimes showing the CLI's progress-spinnner characters spammed en masse

### 🏡 Chores

- **deps:** upgrade to the latest version of codicons
- **log:** always log errors in the debug console too (during development), in addition to the Output panel
- **deps:** bump minimum VS Code version requirement from 1.84.2 to 1.91.0

### 📖 Documentation

- **contributing:** add new "Copywriting" section under "Conventions" with the directives followed when writing user-facing copy for this repo
- **readme:** show correct RID of the Radicle VS Code repo in the rad badge
